name: mitoloji_proje
description: "A new Flutter project."
publish_to: 'none' # Sadece özel kullanım için

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/olympus_background.webp
    - assets/greek_texture.jpg
    - assets/egypttexture.webp
    - assets/history_banner.webp
    - assets/god_banner.webp
    - assets/bg_texture.webp
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: NotoEmoji
      fonts:
        - asset: assets/fonts/NotoEmoji-Regular.ttf
